name: tickert app CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @vue/cli@latest
    - working-directory: "./Aiki-HelpDesk"
    - name: Build App
    - working-directory: "./AiKi-HelpDesk"
    - run: npm install
    - run: npm run build
      env:
        CI: true
