name: CI

on: [push]

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '13.x'
    - name: Build dist
      run: |
        npm install
        sudo npm run build
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
